## 1. Write a Python function to find the Max of three numbers.

In [4]:
def maxOf3(num1,num2,num3):
    if(num1 >= num2) and (num1 >= num3):
        
        max_num = num1

    elif(num2 >= num1) and (num2 >= num3):
        
        max_num = num2

    else:
        
        max_num = num3
               
    print("Max number is : " , max_num)

#calling MaxOf3 function
maxOf3(1,8,2)
    

Max number is :  8


## 2. Write a Python function to sum all the numbers in a list.

In [7]:
def add(lst):
    total = 0 
    for i in lst:
        total += i   
    return total

add([2,4,10])
    

16

## 3. Write a Python script to add a key to a dictionary.

In [35]:
dct = {'a':8, 'b': 10}
print('old dict:',dct)
dct.update({'c':5})
print('updated dct: ',dct)

old dict: {'a': 8, 'b': 10}
updated dct:  {'a': 8, 'b': 10, 'c': 5}


## 4. Write a Python program to iterate over dictionaries using for loops.

In [36]:
dct = {'A': 1, 'B': 2, 'C': 3}
for key, value in dct.items():
    print(key, value)

A 1
B 2
C 3


# 5. Write a Python program to remove duplicates from Dictionary.

In [37]:
student_data = {'id1': 
   {'name': ['Sara'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
 'id2': 
  {'name': ['David'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
 'id3': 
    {'name': ['Sara'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
    }
                
}

dct = {}

for key, value in student_data.items():
    if value not in dct.values():
        dct[key] = value

print(dct)


{'id1': {'name': ['Sara'], 'class': ['V'], 'subject_integration': ['english, math, science']}, 'id2': {'name': ['David'], 'class': ['V'], 'subject_integration': ['english, math, science']}}


## 6. Print First 10 natural numbers using while loop

In [39]:
i = 1
while i<=10:
    print(i)
    i += 1
    



1
2
3
4
5
6
7
8
9
10


## 7. Count the total number of digits in a number

In [43]:
num = 123456789
count = 0

while num > 0:
    count += 1
    num = num // 10
print('Number of digits are:',count)

Number of digits are: 9


## 8. Use else block to display a message “Done” after successful execution of for loop

In [44]:
for i in range(5):
    print(i)
else:
    print('Done')
    


0
1
2
3
4
Done


## 9. Reverse a given integer number

In [45]:
number ='123'
print(number[::-1])

321


## 10. Find the sum of the series upto n terms

In [124]:
num = int(input('Enter your terms: '))
s = 0
addition = 0

for i in range(0, num):
    s = s*10+1
    print(s, end = " ")
    addition = addition + s   
print('\nSum of the series = ', addition )

Enter your terms: 2
1 11 
Sum of the series =  12


## Create a child class Bus that will inherit all of the variables and methods of the Vehicle class

In [57]:
class Vehicle:
    
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        
        
class Bus(Vehicle):
    pass
        
veh = Bus('School Volvo', 180, 12)
print('Vehicle Name:', veh.name,'\n' 'Speed:', veh.max_speed, '\n' 'mileage:', veh.mileage)


Vehicle Name: School Volvo 
Speed: 180 
mileage: 12


## 12.Define property that should have the same value for every class instance Define a class attribute”color” with a default value white. I.e., Every Vehicle should be white.

In [122]:
class Vehicle:
    color = 'white'
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass

obj1 = Bus('School Volvo', 180, 12)
obj2 = Car('Audi Q5', 241, 18)
print('color:', obj1.color, '\t' 'Bus:', obj1.name,'\t' 'speed:', obj1.max_speed, '\t' 'mileage:', obj1.mileage)
print('Color:', obj2.color, '\t' 'Vehicle name:', obj2.name, '\t' 'speed:', obj2.max_speed, '\t' 'mileage:', obj2.mileage)

color: white 	Bus: School Volvo 	speed: 180 	mileage: 12
Color: white 	Vehicle name: Audi Q5 	speed: 241 	mileage: 18


## 13. Create a 4X2 integer array and Prints its attributes

In [114]:
import numpy as np
# import array as ar

arr = np.random.randint(100,size=(8)).reshape(4,2)
print(arr)
print("shape of the array is:" , arr.shape)
print("dimention of the array is :" , arr.ndim)


[[42 95]
 [61 90]
 [76 79]
 [99  1]]
shape of the array is: (4, 2)
dimention of the array is : 2


## 14. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [115]:
arr = np.arange(100, 200, 10).reshape(5, 2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## 15. Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [120]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

result = arrayOne + arrayTwo
print('after addition:\n', result)
print('Square of each element of array:\n',np.square(result))

after addition:
 [[20 39 33]
 [25 25 28]]
Square of each element of array:
 [[ 400 1521 1089]
 [ 625  625  784]]


## 16. Sort following NumPy array

## 1 - sort array by the second row

##  2 - Sort the array by the second column

In [123]:
import numpy as np

arr = np.array([[5, 6, 9], [21 ,18, 27],[15 ,33, 24], [4 ,7, 1]])
print(arr)
print()

# sort by 2nd row
print('sort by second row')
row_sort = arr[:,arr[1].argsort()]
print(row_sort)
print('\n')

# sort by 2nd column
print('sort by 2nd column')
new_sort = arr[arr[:,1].argsort()]
print(new_sort)

[[ 5  6  9]
 [21 18 27]
 [15 33 24]
 [ 4  7  1]]

sort by second row
[[ 6  5  9]
 [18 21 27]
 [33 15 24]
 [ 7  4  1]]


sort by 2nd column
[[ 5  6  9]
 [ 4  7  1]
 [21 18 27]
 [15 33 24]]
